# Generated by Django 6.0.1 on 2026-02-07 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('track', '0002_employee_monthlyentry_monthlypayment_monthlyproduct'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monthlyentry',
            name='balance',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='monthlypayment',
            name='amount',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='monthlyproduct',
            name='price_per_unit',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='monthlyproduct',
            name='total_amount',
            field=models.PositiveIntegerField(),
        ),
    ]
