# Generated by Django 6.0.1 on 2026-02-07 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('track', '0004_warehouseitem_warehousemovement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monthlyentry',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='monthlypayment',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='monthlyproduct',
            name='price_per_unit',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='monthlyproduct',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='warehouseitem',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='warehousemovement',
            name='type',
            field=models.CharField(choices=[('in', 'Items In'), ('out', 'Items Out')], max_length=10),
        ),
    ]
