# Generated by Django 6.0.1 on 2026-02-16 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('track', '0006_transaction_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthlypayment',
            name='currency',
            field=models.CharField(choices=[('uzs', 'UZS'), ('usd', 'USD'), ('afn', 'AFN')], default='uzs', max_length=10),
        ),
        migrations.AddField(
            model_name='monthlyproduct',
            name='currency',
            field=models.CharField(choices=[('uzs', 'UZS'), ('usd', 'USD'), ('afn', 'AFN')], default='uzs', max_length=10),
        ),
        migrations.AddField(
            model_name='monthlyproduct',
            name='unit_type',
            field=models.CharField(choices=[('dona', 'Dona (pieces)'), ('kg', 'Kg (kilogram)')], default='dona', max_length=10),
        ),
        migrations.AddField(
            model_name='warehouseitem',
            name='quantity_kg',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Quantity (kg)'),
        ),
        migrations.AddField(
            model_name='warehousemovement',
            name='quantity_kg',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Quantity (kg)'),
        ),
        migrations.AlterField(
            model_name='monthlyproduct',
            name='quantity',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
    ]
